-- Table: user_accounts
CREATE TABLE IF NOT EXISTS public.user_accounts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  name TEXT NOT NULL,
  tickets_done INTEGER DEFAULT 0 NOT NULL,
  total_tickets INTEGER DEFAULT 10 NOT NULL,
  avatar TEXT DEFAULT 'Avatar1' NOT NULL,
  referral_link TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS for user_accounts
ALTER TABLE public.user_accounts ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view their own accounts" 
  ON public.user_accounts FOR SELECT 
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own accounts" 
  ON public.user_accounts FOR INSERT 
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own accounts" 
  ON public.user_accounts FOR UPDATE 
  USING (auth.uid() = user_id);

CREATE POLICY "Users can delete their own accounts" 
  ON public.user_accounts FOR DELETE 
  USING (auth.uid() = user_id);

-- Table: income_logs
CREATE TABLE IF NOT EXISTS public.income_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  account_id BIGINT REFERENCES public.user_accounts(id) ON DELETE CASCADE,
  account_name TEXT NOT NULL,
  gmto_amount NUMERIC NOT NULL,
  color TEXT DEFAULT 'bg-emerald-500/80' NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS for income_logs
ALTER TABLE public.income_logs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view their own income logs" 
  ON public.income_logs FOR SELECT 
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own income logs" 
  ON public.income_logs FOR INSERT 
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own income logs" 
  ON public.income_logs FOR UPDATE 
  USING (auth.uid() = user_id);

CREATE POLICY "Users can delete their own income logs" 
  ON public.income_logs FOR DELETE 
  USING (auth.uid() = user_id);

-- Table: ticket_logs
CREATE TABLE IF NOT EXISTS public.ticket_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  account_id BIGINT REFERENCES public.user_accounts(id) ON DELETE CASCADE,
  account_name TEXT NOT NULL,
  increment INTEGER NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS for ticket_logs
ALTER TABLE public.ticket_logs ENABLE ROW LEVEL SECURITY;

CREATE POLICY ""Users can view their own ticket logs"" 
  ON public.ticket_logs FOR SELECT 
  USING (auth.uid() = user_id);

CREATE POLICY ""Users can insert their own ticket logs"" 
  ON public.ticket_logs FOR INSERT 
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY ""Users can delete their own ticket logs"" 
  ON public.ticket_logs FOR DELETE 
  USING (auth.uid() = user_id);
