-- Table: global_chats
CREATE TABLE IF NOT EXISTS public.global_chats (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  message TEXT,
  type TEXT DEFAULT 'text' NOT NULL,
  gif_url TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS
ALTER TABLE public.global_chats ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Anyone logged in can view chats" 
  ON public.global_chats FOR SELECT 
  USING (auth.uid() IS NOT NULL);

CREATE POLICY "Users can insert their own chats" 
  ON public.global_chats FOR INSERT 
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can delete their own chats" 
  ON public.global_chats FOR DELETE 
  USING (auth.uid() = user_id);

-- Table: chat_reactions
CREATE TABLE IF NOT EXISTS public.chat_reactions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  message_id BIGINT REFERENCES public.global_chats(id) ON DELETE CASCADE NOT NULL,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  emoji TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  UNIQUE(message_id, user_id, emoji)
);

-- Enable RLS
ALTER TABLE public.chat_reactions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Anyone logged in can view reactions" 
  ON public.chat_reactions FOR SELECT 
  USING (auth.uid() IS NOT NULL);

CREATE POLICY "Users can insert their own reactions" 
  ON public.chat_reactions FOR INSERT 
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can delete their own reactions" 
  ON public.chat_reactions FOR DELETE 
  USING (auth.uid() = user_id);

-- Enable realtime for both tables
alter publication supabase_realtime add table public.global_chats;
alter publication supabase_realtime add table public.chat_reactions;

-- ─────────────────────────────────────────────────────────────────────────────
-- FIX: Allow any logged-in user to READ the name + avatar of other users.
-- Without this, the chat join returns null for other users' names → shows "Player".
-- Run this in Supabase SQL Editor if nicknames are not showing in global chat.
-- ─────────────────────────────────────────────────────────────────────────────
CREATE POLICY IF NOT EXISTS "Authenticated users can view any user name for chat"
  ON public.user_accounts FOR SELECT
  USING (auth.uid() IS NOT NULL);

