-- Table: shoe_inventory_posts
CREATE TABLE IF NOT EXISTS public.shoe_inventory_posts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  account_id BIGINT REFERENCES public.user_accounts(id) ON DELETE CASCADE NOT NULL,
  shoe_count INTEGER NOT NULL DEFAULT 1,
  rarity TEXT NOT NULL DEFAULT 'common',
  visibility TEXT NOT NULL DEFAULT 'private',
  shared_credentials TEXT,
  shared_with_nicknames TEXT[],
  notes TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS
ALTER TABLE public.shoe_inventory_posts ENABLE ROW LEVEL SECURITY;

-- Policy: Owners can always view their own posts
CREATE POLICY "Users can view their own posts" 
  ON public.shoe_inventory_posts FOR SELECT 
  USING (auth.uid() = user_id);

-- Policy: Anyone can view public posts
CREATE POLICY "Anyone can view public posts" 
  ON public.shoe_inventory_posts FOR SELECT 
  USING (visibility = 'public');

-- Policy: Owners can insert
CREATE POLICY "Users can insert their own posts" 
  ON public.shoe_inventory_posts FOR INSERT 
  WITH CHECK (auth.uid() = user_id);

-- Policy: Owners can update
CREATE POLICY "Users can update their own posts" 
  ON public.shoe_inventory_posts FOR UPDATE 
  USING (auth.uid() = user_id);

-- Policy: Owners can delete
CREATE POLICY "Users can delete their own posts" 
  ON public.shoe_inventory_posts FOR DELETE 
  USING (auth.uid() = user_id);

-- Policy: Users can view posts shared with them
CREATE POLICY "Users can view posts shared with them" 
  ON public.shoe_inventory_posts FOR SELECT 
  USING (
    visibility = 'specific_users' AND 
    (auth.jwt() -> 'user_metadata' ->> 'nickname') = ANY(shared_with_nicknames)
  );

-- Policy: Borrowers can view borrowed posts
CREATE POLICY "Borrowers can view borrowed posts" 
  ON public.shoe_inventory_posts FOR SELECT 
  USING (borrowed_by = auth.uid());
