-- ============================================================
-- Temp Email Feature — Migration
-- Uses Mail.tm API for receiving emails (100% free)
-- ============================================================

-- Table: temp_mail_allowed_domains
-- Admin-curated list of Mail.tm domains shown to users
CREATE TABLE IF NOT EXISTS public.temp_mail_allowed_domains (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  domain TEXT UNIQUE NOT NULL,
  is_active BOOLEAN DEFAULT true NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Seed with a default (admin will update from Mail.tm's live list)
INSERT INTO public.temp_mail_allowed_domains (domain, is_active)
VALUES 
  ('mail.tm', true),
  ('aluahmail.xyz', true)
ON CONFLICT (domain) DO NOTHING;

-- Enable RLS
ALTER TABLE public.temp_mail_allowed_domains ENABLE ROW LEVEL SECURITY;

-- Authenticated users can read active domains
CREATE POLICY "Anyone authenticated can view active domains"
  ON public.temp_mail_allowed_domains FOR SELECT
  USING (auth.role() = 'authenticated' AND is_active = true);

-- Service role (admin API) can do everything
CREATE POLICY "Service role full access on domains"
  ON public.temp_mail_allowed_domains FOR ALL
  USING (auth.role() = 'service_role');


-- ============================================================
-- Table: temp_mail_sessions
-- Stores one active Mail.tm mailbox per user
-- ============================================================
CREATE TABLE IF NOT EXISTS public.temp_mail_sessions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL UNIQUE,
  mailtm_account_id TEXT NOT NULL,
  address TEXT NOT NULL,
  mailtm_token TEXT NOT NULL,    -- JWT from Mail.tm (to fetch messages)
  expires_at TIMESTAMP WITH TIME ZONE NOT NULL,  -- now() + 10 min, reset on activity
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS
ALTER TABLE public.temp_mail_sessions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view their own temp mail session"
  ON public.temp_mail_sessions FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own temp mail session"
  ON public.temp_mail_sessions FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own temp mail session"
  ON public.temp_mail_sessions FOR UPDATE
  USING (auth.uid() = user_id);

CREATE POLICY "Users can delete their own temp mail session"
  ON public.temp_mail_sessions FOR DELETE
  USING (auth.uid() = user_id);

CREATE POLICY "Service role full access on sessions"
  ON public.temp_mail_sessions FOR ALL
  USING (auth.role() = 'service_role');
