-- ============================================================
-- TABLE: help_requests
-- Tracks social farming requests between users
-- ============================================================
CREATE TABLE IF NOT EXISTS public.help_requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  requester_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  helper_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  account_id BIGINT REFERENCES public.user_accounts(id) ON DELETE CASCADE NOT NULL,
  status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'accepted', 'rejected', 'completed')),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  UNIQUE(requester_id, helper_id, account_id)
);

-- Enable RLS for help_requests
ALTER TABLE public.help_requests ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view their own requests (as requester or helper)" 
  ON public.help_requests FOR SELECT 
  USING (auth.uid() = requester_id OR auth.uid() = helper_id);

CREATE POLICY "Requesters can insert" 
  ON public.help_requests FOR INSERT 
  WITH CHECK (auth.uid() = requester_id);

CREATE POLICY "Users can update their own requests" 
  ON public.help_requests FOR UPDATE 
  USING (auth.uid() = requester_id OR auth.uid() = helper_id);

CREATE POLICY "Requesters can delete" 
  ON public.help_requests FOR DELETE 
  USING (auth.uid() = requester_id);

-- Enable Realtime for help_requests so floating notifications work instantly
ALTER PUBLICATION supabase_realtime ADD TABLE help_requests;

-- ============================================================
-- RPC: increment_account_ticket
-- Allows owner OR accepted helper to safely increment tickets
-- ============================================================
CREATE OR REPLACE FUNCTION public.increment_account_ticket(p_account_id BIGINT)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_owner_id UUID;
  v_caller_id UUID := auth.uid();
  v_is_helper BOOLEAN := false;
  v_account_name TEXT;
BEGIN
  -- Get account owner and name
  SELECT user_id, name INTO v_owner_id, v_account_name 
  FROM public.user_accounts WHERE id = p_account_id;
  
  IF v_owner_id IS NULL THEN
    RAISE EXCEPTION 'Account not found';
  END IF;

  -- Check if caller is owner
  IF v_caller_id = v_owner_id THEN
    v_is_helper := true;
  ELSE
    -- Check if caller is an accepted helper
    SELECT EXISTS (
      SELECT 1 FROM public.help_requests
      WHERE account_id = p_account_id
      AND helper_id = v_caller_id
      AND status = 'accepted'
    ) INTO v_is_helper;
  END IF;

  IF NOT v_is_helper THEN
    RAISE EXCEPTION 'Unauthorized to increment tickets for this account';
  END IF;

  -- Increment ticket
  UPDATE public.user_accounts
  SET tickets_done = tickets_done + 1
  WHERE id = p_account_id;
  
  -- Log the ticket (using caller's ID but marking it for the account)
  INSERT INTO public.ticket_logs (user_id, account_id, account_name, increment)
  VALUES (v_caller_id, p_account_id, v_account_name, 1);
END;
$$;

GRANT EXECUTE ON FUNCTION public.increment_account_ticket(BIGINT) TO authenticated;
